# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Wrappers for primitive Neural Net (NN) Operations.
"""

from __future__ import print_function
from tensorflow.python.ops.gen_nn_ops import conv2d
from tensorflow.python.ops.gen_nn_ops import relu
from tensorflow.python.ops.nn import max_pool
from tensorflow.python.ops.nn import bidirectional_dynamic_rnn
from tensorflow.python.ops.nn import atrous_conv2d
from tensorflow.python.ops.ctc_ops import ctc_loss
from tensorflow.python.ops.ctc_ops import ctc_greedy_decoder